# Generated by Selenium IDE
import logging

from conftest import app_url, user_pwd
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys


# # Utility functions
def login(driver):
    driver.find_element(By.ID, "email").click()
    driver.find_element(By.ID, "email").send_keys("test-user@example.org")
    driver.find_element(By.ID, "email").send_keys(Keys.ENTER)
    driver.find_element(By.ID, "password").send_keys(user_pwd)
    driver.find_element(By.CSS_SELECTOR, ".submit").click()


# # Test page title @ root
def test_title(driver):
    url = app_url + "/"
    driver.get(url)
    assert driver.title == "datasafeRDM"


# # Test login as test-user@example.org from root
def test_login(driver):
    url = app_url + "/?next=%2F"
    driver.get(url)
    login(driver)
    assert driver.title == "My Data"


# # Test logo-link when logged in and when not logged in
def test_logo_link(driver):
    url = app_url + "/?next=%2F"
    driver.get(url)

    login(driver)
    assert driver.current_url == app_url + "/me/home"

    driver.find_element(By.CSS_SELECTOR, ".ui.image.rdm-logo").click()
    assert driver.current_url == app_url + "/me/home"


# # Test that route /uploads/new shows Login page
def test_uploads_new_login_page(driver):
    url = app_url + "/uploads/new"
    driver.get(url)

    h1_text = 0
    try:
        h1_text = driver.find_element(By.TAG_NAME, "h1").text
    except NoSuchElementException as e:
        logging.warning(e)
    finally:
        assert h1_text == "Log in to account"
