# Copyright (C) 2023-2026 University of Münster.
#
# datasafe-RDM is free software; you can redistribute it and/or
# modify it under the terms of the MIT License; see LICENSE file for more
# details.


[metadata]
name = datasafe-rdm

[options.extras_require]
tests =
    pytest-invenio>=2.1.0,<3.0.0

[options.entry_points]
invenio_base.blueprints =
    datasafe_rdm_views = datasafe_rdm.views:create_blueprint
invenio_assets.webpack =
    datasafe_rdm_theme = datasafe_rdm.webpack:theme
